
src_dirs := .
skip_modules :=

build_probin :=

build_info :=

exe_base := test

debug :=

f90_compiler := gfortran

f90_flags :=
OMP :=

xtr_f90_flags :=
include_flags :=
library_flags :=

MAKEFILE_HOME_DIR := $(HOME)/Programs/FortranDep/Makefiles
include $(MAKEFILE_HOME_DIR)/GMain.mak

