
src_dirs := src ../../utilities
skip_modules :=

build_probin := t

build_info := t

exe_base := test

debug :=

f90_comp := gfortran

f90_flags :=
OMP :=

xtr_f90_flags :=
include_flags :=
library_flags :=

MAKEFILE_HOME_DIR := $(HOME)/Programs/FortranDep/Makefiles
include $(MAKEFILE_HOME_DIR)/GMain.mak

